config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", as: "logout"
  post "pets/search" => "pets#search"
  get '/auth/github/callback' => 'sessions#create'
  
  resources :pets, only: [:index, :show] do
    resources :health_screenings, only: [:index, :edit, :update] 
    get "health_screenings/:status" => "health_screenings#index", as: "health_screenings_status"
  end

  resources :users, only: [:new, :create, :show] do 
    resources :pets, only: [:index, :new, :create, :edit, :update, :destroy ]
    get "/pets/:species" => "pets#index", as: "pets_species"
  end

  resources :health_screenings, only: [:edit, :update, :show]

  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner
  has_many :pets_veterinarians
  has_many :veterinarians, through: :pets_veterinarians
  has_many :health_screenings

  validates :name, presence: true
  validates :species, presence: true, inclusion: {in: %w(Dog Cat)}
  validates :owner_id, presence: true
  validates :birth_date, presence: true
  validates :sex, presence: true, inclusion: {in: %w(Male Female)}

  after_save :set_or_update_age
  after_find :set_or_update_age
  after_initialize :initialize_screenings

  scope :cats, -> {where(species: "Cat")}
  scope :dogs, -> {where(species: "Dog")}

  def initialize_screenings
    if self.health_screenings.empty?
      (self.cat? ? HealthScreening.cat_screenings : HealthScreening.dog_screenings).each do |name, interval|
        self.health_screenings.build(kind: name, renewal_interval: interval, species: self.species)
      end
    end  
  end

  def cat?
    self.species == "Cat"
  end

  def dog?
    self.species == "Dog"
  end

  def set_or_update_age
    now = DateTime.now
    total_months = (now.year*12 + now.month) - (self.birth_date.year*12 + self.birth_date.month)
    years = total_months/12
    months = total_months%12
    if years > 0 && months > 0
      self.age = "#{years} years, #{months} months"
    elsif months > 0  
      self.age = "#{months} months"
    else
      self.age = "#{years} years"
    end
  end

  def self.get_pets_by_user_type(user)
    if user.owner?
      self.all.select{|pet| pet.owner_id == user.id}
    elsif user.vet?
      self.all.select{|pet| pet.veterinarian_ids.include?(user.id)}
    end
  end

  def self.ci_search(attribute, value)
    where("lower(#{attribute}) = ?", value.downcase)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :logged_in_only, only: [:new, :edit, :destroy]
  before_action :owners_only, only: [:new, :edit, :destroy]
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  
  def new
    if User.find_by(:id => params.require(:user_id)) == current_user
      @pet = current_user.pets.build
      render :partial => "pets/form", locals: {pet: @pet}
    elsif current_user
      flash[:alert] = "New pets may only be added to the current user account."
      redirect_to pets_path
    end
  end

  def index
    if params[:user_id]
      @user = User.find_by(:id => params.require(:user_id))
      if @user
        if params[:species]
          @pets = @user.pets.send(params[:species].pluralize)
        else
          @pets = Pet.get_pets_by_user_type(@user)
        end
      else
        flash[:alert] = "Cannot find user."
        redirect_to pets_path
      end
      conditional_render(:index, @pets)
    else
      render partial: "search"
    end 
  end


  def show
    if @pet
      if params[:user_id]
        user = User.find_by(:id => params.require(:user_id))
        if @pet.owner != user || @pet.veterinarians.include?(user)
          flash[:alert] = "The request's pet and user do not match."
          redirect_to pets_path
        end
      end
    else
      flash[:alert] = "Sorry, we were unable to locate that pet in our database."
      redirect_to pets_path
    end
    conditional_render(:show, @pet)
  end


  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      render json: @pet, status: 201
    else
      render :partial => "pets/form", locals: {pet: @pet}
    end
  end

  def edit
    if @pet && @pet.owner != current_user
      flash[:alert] = "Only a pet's owner may edit their information!"
      redirect_to user_path(current_user)
    elsif !@pet
      flash[:alert] = "Sorry, we were unable to locate that pet in our database."
      redirect_to user_path(current_user)
    end
    render :partial => "pets/form", locals: {pet: @pet}
  end

  def update

    if @pet.update(pet_params)
      render json: @pet, status: 201
    else
      render :partial => "pets/form", locals: {pet: @pet}
    end
  end

  def destroy
    @pet.health_screenings.destroy_all
    @pet.destroy
    render json: Pet.new, status: 201
  end

  def search
    pets = if !pet_search_criteria.values.any?(&:empty?)
      Pet.where(owner_id: Owner.ci_find("last_name", pet_search_criteria[:owner_last]).ci_find("first_name", pet_search_criteria[:owner_first]).ids).ci_search("name", pet_search_criteria[:pet_name])
    elsif pet_search_criteria[:owner_first].empty? && pet_search_criteria[:owner_last].empty?
      Pet.ci_search("name", pet_search_criteria[:pet_name])
    elsif pet_search_criteria[:pet_name].empty? && pet_search_criteria[:owner_last].empty?
      Pet.where(owner_id: Owner.ci_find("first_name", pet_search_criteria[:owner_first]).ids)
    elsif pet_search_criteria[:pet_name].empty? && pet_search_criteria[:owner_first].empty?
      Pet.where(owner_id: Owner.ci_find("last_name", pet_search_criteria[:owner_last]).ids)
    elsif pet_search_criteria[:pet_name].empty?
      Pet.where(owner_id: Owner.ci_find("last_name", pet_search_criteria[:owner_last]).ci_find("first_name", pet_search_criteria[:owner_first]).ids)
    elsif pet_search_criteria[:owner_first].empty?
      Pet.where(owner_id: Owner.ci_find("last_name", pet_search_criteria[:owner_last]).ids).ci_search("name", pet_search_criteria[:pet_name])
    elsif pet_search_criteria[:owner_last].empty?
      Pet.where(owner_id: Owner.ci_find("first_name", pet_search_criteria[:owner_first]).ids).ci_search("name", pet_search_criteria[:pet_name])
    end
    render json: pets, status: 201 if !pets.empty?
  end

private
  def pet_params
    params.require(:pet).permit(:name, :birth_date, :species, :sex, :owner_id)
  end

  def pet_search_criteria
    values = params.require(:pet).permit(:name, :owner_first_name, :owner_last_name).values
    { pet_name: values[0], owner_first: values[1], owner_last: values[2]}
  end

  def set_pet
    @pet = Pet.find_by(:id => params.require(:id))
  end

end

app/helpers/pets_helper.rb
module PetsHelper

  def url_for_pet_form(pet)
    if pet.persisted?
      "/users/#{pet.owner.id}/pets/#{pet.id}"
    else
      "/users/#{params[:user_id]}/pets"
    end
  end
end

app/views/pets/_form.html.erb
<%= form_for(pet, url: url_for_pet_form(pet)) do |f| %>

  <%= render "/shared/errors", object: pet %>

  <%= f.hidden_field :owner_id, value: current_user.id %>
  
  <div class="field <%= "field_with_errors" if pet.errors[:name].any? %>">
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
  </div><br>

  <%= f.label :species %>
  <%= f.select :species, ["Dog", "Cat"], selected: pet.species %> 
  <%= f.label :sex %>
  <%= f.select :sex, ['Female', 'Male'], selected: pet.sex %> <br><br>
  <%= f.label :birth_date %> <br>
  <%= f.date_select :birth_date, {start_year: Date.today.year - 20, end_year: Date.today.year} %> <br><br>
  <%= f.submit "Register Pet" %> 
  <%= link_to "Cancel", "#", class: pet.persisted? ? "" : "js-cancel", id: pet.persisted? ? "js-cancel-#{pet.id}" : "" %> <br> <br>
<% end %>

app/views/pets/_info.html.erb
<% if pet.owner == current_user %>
  <p><%= link_to "Edit #{pet.name}'s information", edit_user_pet_path(pet.owner, pet) %></p>
  <p><%= link_to "Remove #{pet.name} from my pets", "/users/#{pet.owner.id}/pets/#{pet.id}", method: :delete %></p>
<% end %>
<ul>
  <li>Type: <%= pet.sex %> <%= pet.species %></li>
  <li>Owner: <%= link_to pet.owner.name, user_path(pet.owner) %></li>
  <li>Age: <%= pet.age %></li>
  <li> <%= "Veterinarian".pluralize(pet.veterinarians.count) %>:
    <ul>
      <% pet.veterinarians.each do |vet| %>
        <li><%= link_to vet.name, user_path(vet) %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/pets/_pet.html.erb
<div id="js-pet-<%= pet.id %>">
  <h4><%= pet.name %></h4>
  <%= render partial: "info", locals: { pet: pet} %>
  <p id="js-screeningsLink-<%= pet.id %>"><%= link_to "View #{pet.name}'s Screenings", pet_health_screenings_path(pet), class: "js-viewScreenings", data: {id: pet.id.to_s, name: pet.name} %></p>
  <div id="js-screenings-<%= pet.id %>"></div>
</div>

app/views/pets/_search.html.erb
  <h2>Find a Pet:</h2>
  <%= form_tag "/pets/search", id: "js-search" do %> <br>
    <%= label_tag "pet[name]", "By pet's name:" %> <br>
    <%= text_field_tag "pet[name]" %> <br><br>
    <!--<%= label_tag "pet[species]", "Species:" %>
    <%= select_tag "pet[species]", options_for_select(["Dog", "Cat"]) %> <br><br>-->
    <%= label_tag "pet[owner_first_name]", "By owner's name:" %> <br>
    <%= text_field_tag "pet[owner_first_name]", nil, placeholder: "first" %>
    <!--<%= label_tag "pet[owner_last_name]", "Owner's Last Name:" %> <br>-->
    <%= text_field_tag "pet[owner_last_name]", nil, placeholder: "last" %> <br> <br>
    <%= submit_tag "Find Pet", id: "js-submitSearch" %> 
    <%= link_to "Cancel", "#", class: "js-cancel" %> <br> <br>
  <% end %>
  <div id="js-searchResults"></div>

app/views/pets/edit.html.erb
<h2>Edit <%= @pet.name %>'s Information:</h2>
<%= render partial: 'form', locals: {pet: @pet} %>

app/views/pets/index.html.erb
<h2> <%= @user.name %>'s <%= (@user.vet? ? "Patient" : "Pet").pluralize(@user.pets.count) %>:</h2>
<p> <%= link_to "All", user_pets_path(@user), class: "js-filterPets", data: {id: @user.id, name: @user.first_name} %> | <%= link_to "Dogs", user_pets_species_path(@user, "dogs"), class: "js-filterPets", data: {id: @user.id, name: @user.first_name, species: "dogs"} %> | <%= link_to "Cats", user_pets_species_path(@user, "cats"), class: "js-filterPets", data: {id: @user.id, name: @user.first_name, species: "cats"} %></p>
<%= render(@pets) %>

app/views/pets/new.html.erb
<h2>Register a New Pet:</h2>
<%= render partial: 'form', locals: {pet: @pet} %>

app/views/pets/show.html.erb
<%= render(@pet) %>