config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", as: "logout"
  post "pets/search" => "pets#search"
  get '/auth/github/callback' => 'sessions#create'
  
  resources :pets, only: [:index, :show] do
    resources :health_screenings, only: [:index, :edit, :update] 
    get "health_screenings/:status" => "health_screenings#index", as: "health_screenings_status"
  end

  resources :users, only: [:new, :create, :show] do 
    resources :pets, only: [:index, :new, :create, :edit, :update, :destroy ]
    get "/pets/:species" => "pets#index", as: "pets_species"
  end

  resources :health_screenings, only: [:edit, :update, :show]

  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/health_screening.rb
class HealthScreening < ApplicationRecord
  belongs_to :pet
  validate :last_updated_cannot_be_prior_to_birth_date
  after_find :update_status

  def last_updated_cannot_be_prior_to_birth_date
    if last_updated && last_updated.year*12 + last_updated.month < pet.birth_date.year*12 + pet.birth_date.month
      errors.add(:last_updated, "Cannot be prior to pet's date of birth.")
    end
  end

  def update_status
    if months_since_last_updated
      if months_since_last_updated > renewal_interval*12
        self.status = "Overdue"
      else
        self.status = "Current"
      end
    else self.status = "Overdue"
    end
    self.save
  end

  def current?
    if last_updated
      if renewal_interval
        months_since_last_updated < renewal_interval*12
      else
        true #some screenings must only be performed once
      end
    else
      false #screening has never been performed
    end
  end

  def months_since_last_updated
    now = DateTime.now
    if last_updated
      (now.year * 12 + now.month) - (last_updated.year * 12 + last_updated.month)
    end
  end

  def self.current
    where(status: "Current")
  end

  def self.overdue
    where(status: "Overdue")
  end

  def self.dog_screenings

    {"Parvovirus" => 3, 
     "CAV-1/Canine Hepatitis" => 3, 
     "CAV-2/Kennel Cough" => 3,
     "Distemper" => 3,
     "Rabies" => 3,
     "Canine Influenza" => 1,
     "Lyme" => 1,
     "Stool Analysis" => 1,
     "Spayed/Neutered" => 1000}

  end

  def self.cat_screenings
    {"Feline Influenza" => 1,
     "Feline Leukemia" => 1,
     "Bordetella" => 1,
     "Rabies" => 1,
     "Stool Analysis" => 1,
     "Feline Distemper" => 3,
     "Feline Herpesvirus" => 3,
     "Calcivirus" => 3,
     "Spayed/Neutered" => 1000}
  end

end

app/controllers/health_screenings_controller.rb
class HealthScreeningsController < ApplicationController
  before_action :logged_in_only, only: [:edit]
  before_action :vets_only, only: [:edit]
  before_action :set_screening, only: [:edit, :update, :show]
  before_action :set_pet, only: [:index]


  def index
    if @pet 
      if params[:status]
        @status = params[:status]
        @health_screenings = @pet.health_screenings.send(@status)
      else
        @health_screenings = HealthScreening.all.select{|hs| hs.pet == @pet}
      end
    else
      flash[:alert] = "Sorry, we were unable to locate that pet in our database."
      redirect_to pets_path
    end
    conditional_render(:index, @health_screenings)
  end

  def show
    if @health_screening
      render json: @health_screening, status: 201
    else
      flash[:alert] = "Invalid request"
      redirect_to pets_path
    end
  end

  def edit
    if !@health_screening || @health_screening.pet != Pet.find_by(:id => params.require(:pet_id))
      flash[:alert] = "Invalid request"
      redirect_to pets_path
    end
    render :partial => "health_screenings/form", locals: {health_screening: @health_screening}
  end

  def update
    if @health_screening.update(screening_params)
      @health_screening.pet.veterinarians << current_user unless @health_screening.pet.veterinarians.include?(current_user)
      @health_screening.pet.save
      render json: @health_screening, status: 201
    else
      render :partial => "health_screenings/form", locals: {health_screening: @health_screening}
    end
  end

  private
  def screening_params
    params.require(:health_screening).permit(:last_updated)
  end

  def set_screening
    @health_screening = HealthScreening.find_by(:id => params.require(:id))
  end

  def set_pet
    @pet = Pet.find_by(:id => params.require(:pet_id))
  end

end

app/helpers/health_screenings_helper.rb
module HealthScreeningsHelper

  def last_updated(screening)
    screening.last_updated ? screening.last_updated.strftime("%B %e, %Y") : "Never"
  end

end

app/views/health_screenings/_form.html.erb
<%= form_for(health_screening) do |f| %>

  <%= render "/shared/errors", object: health_screening %>

  <div class="field <%= "field_with_errors" if health_screening.errors[:last_updated].any? %>">
    <%= f.label :last_updated %>
    <%= f.date_select :last_updated %> <br>
  </div>
  <%= f.submit "Update Record" %> <%= link_to "Cancel", "#", id: "js-cancel-#{health_screening.id}" %>
<% end %>

app/views/health_screenings/_health_screening.html.erb
<p><%= health_screening.kind %> <%= link_to "(update)", edit_pet_health_screening_path(health_screening.pet, health_screening) if logged_in? && current_user.vet? %></p>
<ul>
  <li>Last Updated: <%= last_updated(health_screening) %></li>
  <li>Status: <%= health_screening.status %></li>
</ul>

app/views/health_screenings/edit.html.erb
<h2>Update <%= @health_screening.kind %> for <%= @health_screening.pet.name %>: </h2>
<%= render partial: "form", locals: {health_screening: @health_screening} %>

app/views/health_screenings/index.html.erb
<h2><%= @pet.name %>'s Information</h2>
<%= render partial: "/pets/info", locals: {pet: @pet} %>
<h3><%= @pet.name %>'s <%= @status.capitalize + " " if @status %>Screenings:</h3>
<p><%= link_to "All", pet_health_screenings_path(@pet) %> | <%= link_to "Current", pet_health_screenings_status_path(@pet, "current") %> | <%= link_to "Overdue", pet_health_screenings_status_path(@pet, "overdue") %></p>
<%= render(@health_screenings) %>